#1 Dockerizar ambiente NodeJS.
2020-1-Eulivro/Backend pull request #2
Opened 2020-03-18 12:28 UTC by caiovfernandes

Neste pull request se realizou:

* #1  - Dockerizar ambiente Node.js;
* Implementação e configuração da estrutura de uma aplicação **NodeJs** com **Express**;
* Configuração de uma imagem Docker via **`Dockerfile`**;
* Instanciação de um container a partir da imagem criada via **`docker-compose-local.yml`**.
* Adição de um **`.editorconfig`** e do **`.gitignore`**.

2020-03-18 16:21 UTC, ghost approved these changes
Tudo certinho!

2020-03-18 23:11 UTC, GabrielDVpereira commented
Precisa colocar o node_modules dentro do arquivo .gitIgnore @caiovfernandes

2020-03-19 12:27 UTC, iurisevero approved these changes
Tudo certo!

2020-03-19 17:13 UTC, GabrielDVpereira reviewed
ok!

2020-03-19 22:36 UTC, Ed-vL requested changes

2020-03-19 22:36 UTC, Ed-vL commented on Dockerfile
> +FROM node:11-alpine
Não seria melhor utilizar uma imagem base com versão mais próxima da LTS? Como a: "node:12.2.0-alpine"

2020-03-19 22:36 UTC, Ed-vL commented on Dockerfile
> +RUN mkdir -p /usr/src/app
Esse comando de RUN não é necessário, o WORKDIR abaixo já lida com isso

2020-03-19 22:36 UTC, Ed-vL commented on Dockerfile
> +CMD ["npm", "run", "start"]
O "run" pode ser suprimido também

2021-10-19 18:05 UTC, closed without merging